name: Test Laravel versions with PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [10.*, 11.*, 12.*]
        exclude:
          # Laravel 12 nécessite PHP >= 8.2
          - php: 8.1
            laravel: 12.*

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php }}-${{ matrix.laravel }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install Laravel & dependencies
        run: |
          composer remove laravel/framework --no-interaction || true
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:^8.0" "nesbot/carbon:^2.63" --dev --no-interaction --no-update
          composer update --no-interaction --prefer-dist --no-progress

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
