name: Update Changelog on Release

on:
  release:
    types: [released]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ⚠️ nécessaire pour récupérer tous les tags

      - name: Get previous tag
        id: previoustag
        run: |
          previous_tag=$(git describe --tags --abbrev=0 "${GITHUB_SHA}^" || echo "")
          echo "previous_tag=$previous_tag" >> $GITHUB_OUTPUT

      - name: Generate changelog section
        id: changelog
        run: |
          new_tag="${{ github.event.release.tag_name }}"
          prev_tag="${{ steps.previoustag.outputs.previous_tag }}"

          echo "## $new_tag ($(date +'%Y-%m-%d'))" > new_changes.md

          if [ -n "$prev_tag" ]; then
            echo "" >> new_changes.md
            git log $prev_tag..HEAD --pretty=format:"- %s (%h)" >> new_changes.md
          else
            echo "" >> new_changes.md
            git log --pretty=format:"- %s (%h)" >> new_changes.md
          fi

          echo "" >> new_changes.md
          echo "---" >> new_changes.md

      - name: Update CHANGELOG.md
        run: |
          cat new_changes.md CHANGELOG.md > tmp.md
          mv tmp.md CHANGELOG.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: CHANGELOG.md
          commit_message: "chore: update CHANGELOG for release ${{ github.event.release.tag_name }}"
          branch: changelog-update

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: changelog-update
          base: main
          title: "chore: update CHANGELOG for release ${{ github.event.release.tag_name }}"
          body: "This PR updates the CHANGELOG with commits since the previous release."
          labels: automated-pr

      - name: Auto-merge Pull Request
        if: steps.cpr.outputs.pull-request-url != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          repo-token: ${{ secrets.GITHUB_TOKEN }}
